import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/Goals/HeaderComponent";
import { ClerkProvider } from "@clerk/nextjs";

const mainrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${mainrope.className} antialiased h-screen bg-primary/5`}
        >
          <div className="flex flex-col gap-4 py-2">
            <HeaderComponent />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
