import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/Goals/HeaderComponent";
import { ClerkProvider } from "@clerk/nextjs";
import { Plus } from "lucide-react";

const mainrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  goals,
}: Readonly<{
  children: React.ReactNode;
  goals: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${mainrope.className} antialiased h-screen`}>
          <div className="flex flex-col gap-4 py-2">
            <HeaderComponent />
            {children}
            {goals}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
